const actions = {
  SET_STATE: 'setting/SET_STATE',
  GET_ABOUT: 'setting/GET_ABOUT',
  GET_CONTACT: 'setting/GET_CONTACT',
  GET_HEADER: 'setting/GET_HEADER',
  GET_WHO_WE_ARE: 'setting/GET_WHO_WE_ARE',
  GET_LABELLING: 'setting/GET_LABELLING',
  GET_RESPONSIBILITY: 'setting/GET_RESPONSIBILITY',
  UPDATE_ABOUT: 'setting/UPDATE_ABOUT',
  UPDATE_CONTACT: 'setting/UPDATE_CONTACT',
  UPDATE_HEADER: 'setting/UPDATE_HEADER',
  UPDATE_WHO_WE_ARE: 'setting/UPDATE_WHO_WE_ARE',
  UPDATE_LABELLING: 'setting/UPDATE_LABELLING',
  UPDATE_RESPONSIBILITY: 'setting/UPDATE_RESPONSIBILITY',
}

export default actions
