const actions = {
  SET_STATE: 'blog/SET_STATE',
  ALL_BLOGS: 'blog/ALL_BLOGS',
  CREATE_BLOG:'blog/CREATE_BLOG',
  UPDATE_BLOG:'blog/UPDATE_BLOG',
  PUBLISH_BLOG:'blog/PUBLISH_BLOG',
  DELETE_BLOG:'blog/DELETE_BLOG',
  PUBLIC_BLOGS:'blog/PUBLIC_BLOGS',
  PUBLIC_SINGLE_BLOG:'blog/PUBLIC_SINGLE_BLOG',
  RECENT_BLOGS:'blog/RECENT_BLOGS',
  VIEW_BLOG:'blog/VIEW_BLOG',
  REPLY_BLOG:'blog/REPLY_BLOG',
}

export default actions
